# Generated by Django 3.0.5 on 2020-05-01 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', djrichtextfield.models.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('boss', models.BooleanField(default=False)),
                ('gitProfile', models.URLField(blank=True, max_length=300)),
                ('facebookProfile', models.URLField(blank=True, max_length=300)),
                ('instaProfile', models.URLField(blank=True, max_length=300)),
                ('twitterProfile', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('gitLink', models.URLField(blank=True, max_length=300)),
                ('memebers', models.ManyToManyField(related_name='projects', to='bugTracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('wiki', djrichtextfield.models.RichTextField()),
                ('important', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FRONT', 'FRONTEND'), ('BACK', 'BACKEND')], default='BACK', max_length=50)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('T', 'To be Discussed')], default='P', max_length=50)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bugTracker.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bugTracker.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Uploaded image')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bugTracker.Comment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bugTracker.Issue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileImage', to='bugTracker.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugTracker.Issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='bugTracker.User'),
        ),
    ]
