# Generated by Django 3.0.5 on 2020-05-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creater',
        ),
    ]
