# Generated by Django 3.0.6 on 2020-05-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('gitLink', models.URLField(blank=True, max_length=300)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myprojects', to=settings.AUTH_USER_MODEL)),
                ('memebers', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('wiki', djrichtextfield.models.RichTextField()),
                ('important', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FRONT', 'FRONTEND'), ('BACK', 'BACKEND')], default='BACK', max_length=50)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('T', 'To be Discussed')], default='P', max_length=50)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bugTracker.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', djrichtextfield.models.RichTextField()),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL)),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugTracker.Issue')),
            ],
        ),
    ]
