# Generated by Django 3.0.5 on 2020-05-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0002_auto_20200512_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myprojects', to='bugTracker.User'),
            preserve_default=False,
        ),
    ]
