# Generated by Django 3.0.6 on 2020-05-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('bugTracker', '0002_comment_issue_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Uploaded image')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bugTracker.Comment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bugTracker.Issue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileImage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=40)),
                ('revoke_token', models.CharField(max_length=40)),
                ('expires_in', models.IntegerField()),
                ('pusedo_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
