# Generated by Django 3.0.6 on 2020-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0005_comment_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
